### ISSUE TITLE
地标功能报错

### ISSUE THREAD

**Issue by ppfirework** [wisdommen/UltiTools#46]
可以正常设置地地标
但是不能传送

15:35:50] [Craft Scheduler Thread - 9/WARN]: [UltiTools] Plugin UltiTools v5.0.2 generated an exception while executing task 17419
>java.lang.IllegalStateException: PlayerTeleportEvent cannot be triggered asynchronously from another thread.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[purpur-1.16.5.jar:3002-Spigot-138d451-085fe67]
at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleport(CraftPlayer.java:662) ~[purpur-1.16.5.jar:3002-Spigot-138d451-085fe67]
at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:475) ~[purpur-1.16.5.jar:3002-Spigot-138d451-085fe67]
at com.ultikits.ultitools.commands.WarpCommands$1.run(WarpCommands.java:48) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[purpur-1.16.5.jar:3002-Spigot-138d451-085fe67]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [purpur-1.16.5.jar:3002-Spigot-138d451-085fe67]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]

插件是最新版
核心spigot
游戏版本1.16.5

**Comment by wisdommen** [comment]
Ok,马上修复，感谢反馈

**Comment by wisdommen** [comment]
已在5.0.3版本修复，请关注一下更新

**Comment by wisdommen** [comment]
已更新，请前往下载最新版本以修复问题
