### ISSUE TITLE
锁箱子系统报错

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [wisdommen/UltiTools#68]
当玩家使用/lock指令的时候出现An intrnal error has occured
[lockerror.log](https://github.com/wisdommen/UltiTools/files/7037006/lockerror.log)

**Comment by J4ckTh3R1pper** [comment]
[06:18:24] [Server thread/INFO]: J4ckTh3R1pper issued server command: /lock
[06:18:24] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lock' in plugin UltiTools v5.1.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:776) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1124) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.ultikits.ultitools.commands.LockCommands.onPlayerCommand(LockCommands.java:21) ~[?:?]
	at com.ultikits.abstracts.AbstractPlayerCommandExecutor.onCommand(AbstractPlayerCommandExecutor.java:19) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.17.1.jar:3226-Spigot-3c1fc60-a955f15]
	... 19 mor

**Comment by J4ckTh3R1pper** [comment]
使用服务端版本:Spigot 1.17.1

**Comment by qianmo2233** [comment]
这个在下个版本修复

**Comment by J4ckTh3R1pper** [comment]
> 这个在下个版本修复
非常感谢！

**Comment by qianmo2233** [comment]
如果您急用的话可以参照[这个](https://github.com/wisdommen/UltiTools/pull/67)自行修改代码并构建，完美解决问题

**Comment by J4ckTh3R1pper** [comment]
> 如果您急用的话可以参照[这个](https://github.com/wisdommen/UltiTools/pull/67)自行修改代码并构建，完美解决问题

我按照那两个文件对源码进行修改之后编译并替换了class文件，完美解决！非常感谢

**Comment by qianmo2233** [comment]
刚才才这个issue又打开了，还以为又有什么事😂
